//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.04 at 10:24:07 AM CEST 
//


package org.jboss.jaxb.intros.configmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Class complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Class">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlAccessorType" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlType" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlRootElement" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlTransient" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlJavaTypeAdapter" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}Field" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}Method" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Class", propOrder = {
    "xmlAccessorType",
    "xmlType",
    "xmlRootElement",
    "xmlTransient",
    "xmlJavaTypeAdapter",
    "field",
    "method"
})
public class ClassIntroConfig {

    @XmlElement(name = "XmlAccessorType")
    protected XmlAccessorTypeIntro xmlAccessorType;
    @XmlElement(name = "XmlType")
    protected XmlTypeIntro xmlType;
    @XmlElement(name = "XmlRootElement")
    protected XmlRootElementIntro xmlRootElement;
    @XmlElement(name = "XmlTransient")
    protected XmlTransientIntro xmlTransient;
    @XmlElement(name = "XmlJavaTypeAdapter")
    protected XmlJavaTypeAdapterIntro xmlJavaTypeAdapter;
    @XmlElement(name = "Field")
    protected List<FieldIntroConfig> field;
    @XmlElement(name = "Method")
    protected List<MethodIntroConfig> method;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the xmlAccessorType property.
     * 
     * @return
     *     possible object is
     *     {@link XmlAccessorTypeIntro }
     *     
     */
    public XmlAccessorTypeIntro getXmlAccessorType() {
        return xmlAccessorType;
    }

    /**
     * Sets the value of the xmlAccessorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlAccessorTypeIntro }
     *     
     */
    public void setXmlAccessorType(XmlAccessorTypeIntro value) {
        this.xmlAccessorType = value;
    }

    /**
     * Gets the value of the xmlType property.
     * 
     * @return
     *     possible object is
     *     {@link XmlTypeIntro }
     *     
     */
    public XmlTypeIntro getXmlType() {
        return xmlType;
    }

    /**
     * Sets the value of the xmlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlTypeIntro }
     *     
     */
    public void setXmlType(XmlTypeIntro value) {
        this.xmlType = value;
    }

    /**
     * Gets the value of the xmlRootElement property.
     * 
     * @return
     *     possible object is
     *     {@link XmlRootElementIntro }
     *     
     */
    public XmlRootElementIntro getXmlRootElement() {
        return xmlRootElement;
    }

    /**
     * Sets the value of the xmlRootElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlRootElementIntro }
     *     
     */
    public void setXmlRootElement(XmlRootElementIntro value) {
        this.xmlRootElement = value;
    }

    /**
     * Gets the value of the xmlTransient property.
     * 
     * @return
     *     possible object is
     *     {@link XmlTransientIntro }
     *     
     */
    public XmlTransientIntro getXmlTransient() {
        return xmlTransient;
    }

    /**
     * Sets the value of the xmlTransient property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlTransientIntro }
     *     
     */
    public void setXmlTransient(XmlTransientIntro value) {
        this.xmlTransient = value;
    }

    /**
     * Gets the value of the xmlJavaTypeAdapter property.
     * 
     * @return
     *     possible object is
     *     {@link XmlJavaTypeAdapterIntro }
     *     
     */
    public XmlJavaTypeAdapterIntro getXmlJavaTypeAdapter() {
        return xmlJavaTypeAdapter;
    }

    /**
     * Sets the value of the xmlJavaTypeAdapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlJavaTypeAdapterIntro }
     *     
     */
    public void setXmlJavaTypeAdapter(XmlJavaTypeAdapterIntro value) {
        this.xmlJavaTypeAdapter = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldIntroConfig }
     * 
     * 
     */
    public List<FieldIntroConfig> getField() {
        if (field == null) {
            field = new ArrayList<FieldIntroConfig>();
        }
        return this.field;
    }

    /**
     * Gets the value of the method property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the method property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MethodIntroConfig }
     * 
     * 
     */
    public List<MethodIntroConfig> getMethod() {
        if (method == null) {
            method = new ArrayList<MethodIntroConfig>();
        }
        return this.method;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
