//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.04 at 10:24:07 AM CEST 
//


package org.jboss.jaxb.intros.configmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Java Class Member (Field, Method Constructor) JAXB Annotation Introductions configuration base type.
 * 
 * <p>Java class for class-member-intro-config complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="class-member-intro-config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlElement" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlAttribute" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlTransient" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlID" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlIDREF" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlElementWrapper" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlJavaTypeAdapter" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "class-member-intro-config", propOrder = {
    "xmlElement",
    "xmlAttribute",
    "xmlTransient",
    "xmlID",
    "xmlIDREF",
    "xmlElementWrapper",
    "xmlJavaTypeAdapter"
})
@XmlSeeAlso({
    FieldIntroConfig.class,
    MethodIntroConfig.class
})
public class ClassMemberIntroConfig {

    @XmlElement(name = "XmlElement")
    protected XmlElementIntro xmlElement;
    @XmlElement(name = "XmlAttribute")
    protected XmlAttributeIntro xmlAttribute;
    @XmlElement(name = "XmlTransient")
    protected XmlTransientIntro xmlTransient;
    @XmlElement(name = "XmlID")
    protected XmlIDIntro xmlID;
    @XmlElement(name = "XmlIDREF")
    protected XmlIDREFIntro xmlIDREF;
    @XmlElement(name = "XmlElementWrapper")
    protected XmlElementWrapperIntro xmlElementWrapper;
    @XmlElement(name = "XmlJavaTypeAdapter")
    protected XmlJavaTypeAdapterIntro xmlJavaTypeAdapter;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the xmlElement property.
     * 
     * @return
     *     possible object is
     *     {@link XmlElementIntro }
     *     
     */
    public XmlElementIntro getXmlElement() {
        return xmlElement;
    }

    /**
     * Sets the value of the xmlElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlElementIntro }
     *     
     */
    public void setXmlElement(XmlElementIntro value) {
        this.xmlElement = value;
    }

    /**
     * Gets the value of the xmlAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link XmlAttributeIntro }
     *     
     */
    public XmlAttributeIntro getXmlAttribute() {
        return xmlAttribute;
    }

    /**
     * Sets the value of the xmlAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlAttributeIntro }
     *     
     */
    public void setXmlAttribute(XmlAttributeIntro value) {
        this.xmlAttribute = value;
    }

    /**
     * Gets the value of the xmlTransient property.
     * 
     * @return
     *     possible object is
     *     {@link XmlTransientIntro }
     *     
     */
    public XmlTransientIntro getXmlTransient() {
        return xmlTransient;
    }

    /**
     * Sets the value of the xmlTransient property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlTransientIntro }
     *     
     */
    public void setXmlTransient(XmlTransientIntro value) {
        this.xmlTransient = value;
    }

    /**
     * Gets the value of the xmlID property.
     * 
     * @return
     *     possible object is
     *     {@link XmlIDIntro }
     *     
     */
    public XmlIDIntro getXmlID() {
        return xmlID;
    }

    /**
     * Sets the value of the xmlID property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlIDIntro }
     *     
     */
    public void setXmlID(XmlIDIntro value) {
        this.xmlID = value;
    }

    /**
     * Gets the value of the xmlIDREF property.
     * 
     * @return
     *     possible object is
     *     {@link XmlIDREFIntro }
     *     
     */
    public XmlIDREFIntro getXmlIDREF() {
        return xmlIDREF;
    }

    /**
     * Sets the value of the xmlIDREF property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlIDREFIntro }
     *     
     */
    public void setXmlIDREF(XmlIDREFIntro value) {
        this.xmlIDREF = value;
    }

    /**
     * Gets the value of the xmlElementWrapper property.
     * 
     * @return
     *     possible object is
     *     {@link XmlElementWrapperIntro }
     *     
     */
    public XmlElementWrapperIntro getXmlElementWrapper() {
        return xmlElementWrapper;
    }

    /**
     * Sets the value of the xmlElementWrapper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlElementWrapperIntro }
     *     
     */
    public void setXmlElementWrapper(XmlElementWrapperIntro value) {
        this.xmlElementWrapper = value;
    }

    /**
     * Gets the value of the xmlJavaTypeAdapter property.
     * 
     * @return
     *     possible object is
     *     {@link XmlJavaTypeAdapterIntro }
     *     
     */
    public XmlJavaTypeAdapterIntro getXmlJavaTypeAdapter() {
        return xmlJavaTypeAdapter;
    }

    /**
     * Sets the value of the xmlJavaTypeAdapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlJavaTypeAdapterIntro }
     *     
     */
    public void setXmlJavaTypeAdapter(XmlJavaTypeAdapterIntro value) {
        this.xmlJavaTypeAdapter = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
