//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.21 at 10:20:40 PM GMT 
//


package org.jboss.jaxb.intros.configmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Java Class Member (Field, Method Constructor) JAXB Annotation Introductions configuration base type.
 * <p/>
 * <p>Java class for class-member-intro-config complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="class-member-intro-config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlElement" minOccurs="0"/>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}XmlAttribute" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "class-member-intro-config", propOrder = {
  "xmlElement",
  "xmlAttribute"
  })
@XmlSeeAlso({
  MethodIntroConfig.class,
  FieldIntroConfig.class
  })
public class ClassMemberIntroConfig
{

   @XmlElement(name = "XmlElement")
   protected XmlElementIntro xmlElement;
   @XmlElement(name = "XmlAttribute")
   protected XmlAttributeIntro xmlAttribute;
   @XmlAttribute(required = true)
   @XmlSchemaType(name = "anySimpleType")
   protected String name;

   /**
    * Gets the value of the xmlElement property.
    *
    * @return possible object is
    *         {@link XmlElementIntro }
    */
   public XmlElementIntro getXmlElement()
   {
      return xmlElement;
   }

   /**
    * Sets the value of the xmlElement property.
    *
    * @param value allowed object is
    *              {@link XmlElementIntro }
    */
   public void setXmlElement(XmlElementIntro value)
   {
      this.xmlElement = value;
   }

   /**
    * Gets the value of the xmlAttribute property.
    *
    * @return possible object is
    *         {@link XmlAttributeIntro }
    */
   public XmlAttributeIntro getXmlAttribute()
   {
      return xmlAttribute;
   }

   /**
    * Sets the value of the xmlAttribute property.
    *
    * @param value allowed object is
    *              {@link XmlAttributeIntro }
    */
   public void setXmlAttribute(XmlAttributeIntro value)
   {
      this.xmlAttribute = value;
   }

   /**
    * Gets the value of the name property.
    *
    * @return possible object is
    *         {@link String }
    */
   public String getName()
   {
      return name;
   }

   /**
    * Sets the value of the name property.
    *
    * @param value allowed object is
    *              {@link String }
    */
   public void setName(String value)
   {
      this.name = value;
   }

}
