//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.04 at 10:24:07 AM CEST 
//


package org.jboss.jaxb.intros.configmodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Field complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * {@code
 * <complexType name="Field">
 *   <complexContent>
 *     <extension base="{http://www.jboss.org/xsd/jaxb/intros}class-member-intro-config">
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }
 * }
</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Field")
public class FieldIntroConfig
    extends ClassMemberIntroConfig
{


}
