//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.21 at 10:20:40 PM GMT 
//


package org.jboss.jaxb.intros.configmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.jboss.org/xsd/jaxb/intros}Class" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="default-namespace" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
  "clazz"
  })
@XmlRootElement(name = "jaxb-intros")
public class JaxbIntros
{

   @XmlElement(name = "Class", required = true)
   protected List<ClassIntroConfig> clazz;
   @XmlAttribute(name = "default-namespace")
   @XmlSchemaType(name = "anySimpleType")
   protected String defaultNamespace;

   /**
    * Gets the value of the clazz property.
    * <p/>
    * <p/>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the JAXB object.
    * This is why there is not a <CODE>set</CODE> method for the clazz property.
    * <p/>
    * <p/>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getClazz().add(newItem);
    * </pre>
    * <p/>
    * <p/>
    * <p/>
    * Objects of the following type(s) are allowed in the list
    * {@link ClassIntroConfig }
    */
   public List<ClassIntroConfig> getClazz()
   {
      if (clazz == null)
      {
         clazz = new ArrayList<ClassIntroConfig>();
      }
      return this.clazz;
   }

   /**
    * Gets the value of the defaultNamespace property.
    *
    * @return possible object is
    *         {@link String }
    */
   public String getDefaultNamespace()
   {
      return defaultNamespace;
   }

   /**
    * Sets the value of the defaultNamespace property.
    *
    * @param value allowed object is
    *              {@link String }
    */
   public void setDefaultNamespace(String value)
   {
      this.defaultNamespace = value;
   }

}
