//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.04 at 10:24:07 AM CEST 
//


package org.jboss.jaxb.intros.configmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jboss.jaxb.intros.configmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClassMemberIntroConfig_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "class-member-intro-config");
    private final static QName _XmlJavaTypeAdapter_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "XmlJavaTypeAdapter");
    private final static QName _Field_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "Field");
    private final static QName _XmlElementWrapper_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "XmlElementWrapper");
    private final static QName _Method_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "Method");
    private final static QName _XmlIDREF_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "XmlIDREF");
    private final static QName _XmlElement_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "XmlElement");
    private final static QName _XmlAttribute_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "XmlAttribute");
    private final static QName _XmlRootElement_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "XmlRootElement");
    private final static QName _XmlType_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "XmlType");
    private final static QName _XmlTransient_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "XmlTransient");
    private final static QName _XmlID_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "XmlID");
    private final static QName _Class_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "Class");
    private final static QName _XmlAccessorType_QNAME = new QName("http://www.jboss.org/xsd/jaxb/intros", "XmlAccessorType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jboss.jaxb.intros.configmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlRootElementIntro }
     * 
     */
    public XmlRootElementIntro createXmlRootElementIntro() {
        return new XmlRootElementIntro();
    }

    /**
     * Create an instance of {@link FieldIntroConfig }
     * 
     */
    public FieldIntroConfig createFieldIntroConfig() {
        return new FieldIntroConfig();
    }

    /**
     * Create an instance of {@link XmlIDIntro }
     * 
     */
    public XmlIDIntro createXmlIDIntro() {
        return new XmlIDIntro();
    }

    /**
     * Create an instance of {@link XmlAccessorTypeIntro }
     * 
     */
    public XmlAccessorTypeIntro createXmlAccessorTypeIntro() {
        return new XmlAccessorTypeIntro();
    }

    /**
     * Create an instance of {@link JaxbIntros }
     * 
     */
    public JaxbIntros createJaxbIntros() {
        return new JaxbIntros();
    }

    /**
     * Create an instance of {@link XmlJavaTypeAdapterIntro }
     * 
     */
    public XmlJavaTypeAdapterIntro createXmlJavaTypeAdapterIntro() {
        return new XmlJavaTypeAdapterIntro();
    }

    /**
     * Create an instance of {@link ClassMemberIntroConfig }
     * 
     */
    public ClassMemberIntroConfig createClassMemberIntroConfig() {
        return new ClassMemberIntroConfig();
    }

    /**
     * Create an instance of {@link XmlElementIntro }
     * 
     */
    public XmlElementIntro createXmlElementIntro() {
        return new XmlElementIntro();
    }

    /**
     * Create an instance of {@link XmlTypeIntro }
     * 
     */
    public XmlTypeIntro createXmlTypeIntro() {
        return new XmlTypeIntro();
    }

    /**
     * Create an instance of {@link XmlAttributeIntro }
     * 
     */
    public XmlAttributeIntro createXmlAttributeIntro() {
        return new XmlAttributeIntro();
    }

    /**
     * Create an instance of {@link MethodIntroConfig }
     * 
     */
    public MethodIntroConfig createMethodIntroConfig() {
        return new MethodIntroConfig();
    }

    /**
     * Create an instance of {@link ClassIntroConfig }
     * 
     */
    public ClassIntroConfig createClassIntroConfig() {
        return new ClassIntroConfig();
    }

    /**
     * Create an instance of {@link XmlElementWrapperIntro }
     * 
     */
    public XmlElementWrapperIntro createXmlElementWrapperIntro() {
        return new XmlElementWrapperIntro();
    }

    /**
     * Create an instance of {@link XmlTransientIntro }
     * 
     */
    public XmlTransientIntro createXmlTransientIntro() {
        return new XmlTransientIntro();
    }

    /**
     * Create an instance of {@link XmlIDREFIntro }
     * 
     */
    public XmlIDREFIntro createXmlIDREFIntro() {
        return new XmlIDREFIntro();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "class-member-intro-config")
    public JAXBElement<Object> createClassMemberIntroConfig(Object value) {
        return new JAXBElement<Object>(_ClassMemberIntroConfig_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlJavaTypeAdapterIntro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "XmlJavaTypeAdapter")
    public JAXBElement<XmlJavaTypeAdapterIntro> createXmlJavaTypeAdapter(XmlJavaTypeAdapterIntro value) {
        return new JAXBElement<XmlJavaTypeAdapterIntro>(_XmlJavaTypeAdapter_QNAME, XmlJavaTypeAdapterIntro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldIntroConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "Field", substitutionHeadNamespace = "http://www.jboss.org/xsd/jaxb/intros", substitutionHeadName = "class-member-intro-config")
    public JAXBElement<FieldIntroConfig> createField(FieldIntroConfig value) {
        return new JAXBElement<FieldIntroConfig>(_Field_QNAME, FieldIntroConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlElementWrapperIntro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "XmlElementWrapper")
    public JAXBElement<XmlElementWrapperIntro> createXmlElementWrapper(XmlElementWrapperIntro value) {
        return new JAXBElement<XmlElementWrapperIntro>(_XmlElementWrapper_QNAME, XmlElementWrapperIntro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MethodIntroConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "Method", substitutionHeadNamespace = "http://www.jboss.org/xsd/jaxb/intros", substitutionHeadName = "class-member-intro-config")
    public JAXBElement<MethodIntroConfig> createMethod(MethodIntroConfig value) {
        return new JAXBElement<MethodIntroConfig>(_Method_QNAME, MethodIntroConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlIDREFIntro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "XmlIDREF")
    public JAXBElement<XmlIDREFIntro> createXmlIDREF(XmlIDREFIntro value) {
        return new JAXBElement<XmlIDREFIntro>(_XmlIDREF_QNAME, XmlIDREFIntro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlElementIntro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "XmlElement")
    public JAXBElement<XmlElementIntro> createXmlElement(XmlElementIntro value) {
        return new JAXBElement<XmlElementIntro>(_XmlElement_QNAME, XmlElementIntro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlAttributeIntro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "XmlAttribute")
    public JAXBElement<XmlAttributeIntro> createXmlAttribute(XmlAttributeIntro value) {
        return new JAXBElement<XmlAttributeIntro>(_XmlAttribute_QNAME, XmlAttributeIntro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRootElementIntro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "XmlRootElement")
    public JAXBElement<XmlRootElementIntro> createXmlRootElement(XmlRootElementIntro value) {
        return new JAXBElement<XmlRootElementIntro>(_XmlRootElement_QNAME, XmlRootElementIntro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlTypeIntro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "XmlType")
    public JAXBElement<XmlTypeIntro> createXmlType(XmlTypeIntro value) {
        return new JAXBElement<XmlTypeIntro>(_XmlType_QNAME, XmlTypeIntro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlTransientIntro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "XmlTransient")
    public JAXBElement<XmlTransientIntro> createXmlTransient(XmlTransientIntro value) {
        return new JAXBElement<XmlTransientIntro>(_XmlTransient_QNAME, XmlTransientIntro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlIDIntro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "XmlID")
    public JAXBElement<XmlIDIntro> createXmlID(XmlIDIntro value) {
        return new JAXBElement<XmlIDIntro>(_XmlID_QNAME, XmlIDIntro.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassIntroConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "Class")
    public JAXBElement<ClassIntroConfig> createClass(ClassIntroConfig value) {
        return new JAXBElement<ClassIntroConfig>(_Class_QNAME, ClassIntroConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlAccessorTypeIntro }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jboss.org/xsd/jaxb/intros", name = "XmlAccessorType")
    public JAXBElement<XmlAccessorTypeIntro> createXmlAccessorType(XmlAccessorTypeIntro value) {
        return new JAXBElement<XmlAccessorTypeIntro>(_XmlAccessorType_QNAME, XmlAccessorTypeIntro.class, null, value);
    }

}
