//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.21 at 10:20:40 PM GMT 
//


package org.jboss.jaxb.intros.configmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for XmlAccessorType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="XmlAccessorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="value" default="NONE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="PROPERTY"/>
 *             &lt;enumeration value="FIELD"/>
 *             &lt;enumeration value="PUBLIC_MEMBER"/>
 *             &lt;enumeration value="NONE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlAccessorType")
public class XmlAccessorTypeIntro
{

   @XmlAttribute
   @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
   protected String value;

   /**
    * Gets the value of the value property.
    *
    * @return possible object is
    *         {@link String }
    */
   public String getValue()
   {
      if (value == null)
      {
         return "NONE";
      }
      else
      {
         return value;
      }
   }

   /**
    * Sets the value of the value property.
    *
    * @param value allowed object is
    *              {@link String }
    */
   public void setValue(String value)
   {
      this.value = value;
   }

}
